version: '3.8'
services:
  samsdb:
    container_name: samsdb
    restart: always
    ports:
      - 27018:27017
    env_file:
      - ./envfiles/mongodb.env
  
  samsapp:
    container_name: samsapp
    ports:
      - 7001:7001
    env_file:
      - ./envfiles/testsamsapp.env
    
    
