version: '3.8'
services:
  samsdb:
    container_name: samsdb
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./envfiles/mongodb.env
  
  samsapp:
    container_name: samsapp
    ports:
      - 80:7001
    env_file:
      - ./envfiles/prodsamsapp.env
    
    
